In [63]:
import pandas as pd 
import numpy as np

In [64]:
df=pd.read_csv(r"C:\Users\ashis\Downloads\large_data_cleaning_practice.csv")

load the dataset using pandas

In [65]:
df

,customer_id,name,age,email,city,signup_date,salary
0,1,NaN,131.0,invalid_email,Bangalore,2023-03-07 0:00:00,400486.0
1,2,Neha,19.0,neha@outlook.com,Bangalore,2023-11-12 0:00:00,NaN
2,3,Rahul,145.0,rahul@yahoo.com,Chennai,2023-12-27 0:00:00,64898.0
3,4,Riya,19.0,riya@outlook.com,MUMBAI,2024-07-26 0:00:00,NaN
4,5,Neha,-2.0,neha@yahoo.com,MUMBAI,2022-09-22 0:00:00,NaN
...,...,...,...,...,...,...,...
5045,46,NaN,28.0,invalid_email,Delhi,2023-08-29 0:00:00,NaN
5046,47,Rahul,148.0,rahulgmail.com,delhi,2023-11-16 0:00:00,38627.0
5047,48,John,53.0,john@yahoo.com,delhi,2023-03-22 0:00:00,66281.0
5048,49,John,-2.0,john@yahoo.com,Chennai,2022-01-26 0:00:00,83236.0
5049,50,John,68.0,invalid_email,Delhi,2022-11-30 0:00:00,246114.0

## data inspection

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.describe()

df.head() allows you to visually spot errors like "invalid_email".

df.info() reveals data type errors—for instance, signup_date being text instead of a date.

df.describe() highlights Outliers (like ages of -10 or 150).

df.isnull().sum() pinpoint exactly which columns need filling (e.g., 1,642 missing salaries).

### check for null values

In [ ]:
df.isnull().sum()

### check for duplicate values

In [ ]:
df.duplicated().sum()    # shows full row duplicates

In [ ]:
df[df['email'].duplicated(keep = False)]

In [ ]:
df[df.duplicated(subset='customer_id',keep=False)]

In [ ]:
df[df.duplicated(subset='email',keep = False)]

## *lets start with data cleaning process

### make a copy of the data

In [66]:
df_clean=df.copy()

In [67]:
df_clean

,customer_id,name,age,email,city,signup_date,salary
0,1,NaN,131.0,invalid_email,Bangalore,2023-03-07 0:00:00,400486.0
1,2,Neha,19.0,neha@outlook.com,Bangalore,2023-11-12 0:00:00,NaN
2,3,Rahul,145.0,rahul@yahoo.com,Chennai,2023-12-27 0:00:00,64898.0
3,4,Riya,19.0,riya@outlook.com,MUMBAI,2024-07-26 0:00:00,NaN
4,5,Neha,-2.0,neha@yahoo.com,MUMBAI,2022-09-22 0:00:00,NaN
...,...,...,...,...,...,...,...
5045,46,NaN,28.0,invalid_email,Delhi,2023-08-29 0:00:00,NaN
5046,47,Rahul,148.0,rahulgmail.com,delhi,2023-11-16 0:00:00,38627.0
5047,48,John,53.0,john@yahoo.com,delhi,2023-03-22 0:00:00,66281.0
5048,49,John,-2.0,john@yahoo.com,Chennai,2022-01-26 0:00:00,83236.0
5049,50,John,68.0,invalid_email,Delhi,2022-11-30 0:00:00,246114.0

## standardize column name

In [68]:
df_clean.columns.str.lower().str.strip().str.replace(" ","_")

Index(['customer_id', 'name', 'age', 'email', 'city', 'signup_date', 'salary'], dtype='object')

In [ ]:
df.dtypes

## handel missing values

In [ ]:
df_clean.isnull().sum()

i think there are many null values and to delete all the null will not be good
so, i will impute it with mean ,median,mode and unknow for categorical columns

In [ ]:
# df_clean=df_clean.dropna()     this will drop all the null values

In [61]:
df_clean['age'].median()

np.float64(43.0)

In [69]:
df_clean.loc[(df_clean['age'] < 0) | (df_clean['age'] > 100), 'age'] = np.nan

now i had changed all the ouliers and inconstint values to null

In [70]:
df_clean['age']=df_clean['age'].fillna(df_clean['age'].median())

Handling missing values depends on business requirements: we may keep them as NULL or impute using methods like mean or median. I prefer median when data has outliers, as it provides a more robust and less skewed estimate.

### change all the missing values is name column to unknown

In [71]:
df_clean['name']=df_clean['name'].fillna('unknown')

### same goes for city

In [72]:
df_clean['city']=df_clean['city'].fillna('unknown')

### first i check null values in salary column

In [75]:
df_clean['salary'].isnull().sum()

np.int64(0)

In [ ]:
df_clean['salary'].median()

### i had impute using median in salary column

In [74]:
df_clean['salary']=df_clean['salary'].fillna(df_clean['salary'].median())

### now all the missing values are updated except signup_date as i want to keep all the missing values to null

###  now lets check duplicates records

In [76]:
df[df_clean.duplicated(subset=['customer_id','email'],keep= False)]

,customer_id,name,age,email,city,signup_date,salary
0,1,NaN,131.0,invalid_email,Bangalore,2023-03-07 0:00:00,400486.0
1,2,Neha,19.0,neha@outlook.com,Bangalore,2023-11-12 0:00:00,NaN
2,3,Rahul,145.0,rahul@yahoo.com,Chennai,2023-12-27 0:00:00,64898.0
3,4,Riya,19.0,riya@outlook.com,MUMBAI,2024-07-26 0:00:00,NaN
4,5,Neha,-2.0,neha@yahoo.com,MUMBAI,2022-09-22 0:00:00,NaN
...,...,...,...,...,...,...,...
5045,46,NaN,28.0,invalid_email,Delhi,2023-08-29 0:00:00,NaN
5046,47,Rahul,148.0,rahulgmail.com,delhi,2023-11-16 0:00:00,38627.0
5047,48,John,53.0,john@yahoo.com,delhi,2023-03-22 0:00:00,66281.0
5048,49,John,-2.0,john@yahoo.com,Chennai,2022-01-26 0:00:00,83236.0
5049,50,John,68.0,invalid_email,Delhi,2022-11-30 0:00:00,246114.0

In [78]:
df_clean[df_clean.duplicated(keep=False)]

,customer_id,name,age,email,city,signup_date,salary
0,1,unknown,42.0,invalid_email,Bangalore,2023-03-07 0:00:00,400486.0
1,2,Neha,19.0,neha@outlook.com,Bangalore,2023-11-12 0:00:00,116747.0
2,3,Rahul,42.0,rahul@yahoo.com,Chennai,2023-12-27 0:00:00,64898.0
3,4,Riya,19.0,riya@outlook.com,MUMBAI,2024-07-26 0:00:00,116747.0
4,5,Neha,42.0,neha@yahoo.com,MUMBAI,2022-09-22 0:00:00,116747.0
...,...,...,...,...,...,...,...
5045,46,unknown,28.0,invalid_email,Delhi,2023-08-29 0:00:00,116747.0
5046,47,Rahul,42.0,rahulgmail.com,delhi,2023-11-16 0:00:00,38627.0
5047,48,John,53.0,john@yahoo.com,delhi,2023-03-22 0:00:00,66281.0
5048,49,John,42.0,john@yahoo.com,Chennai,2022-01-26 0:00:00,83236.0
5049,50,John,68.0,invalid_email,Delhi,2022-11-30 0:00:00,246114.0

### first check for exact duplicates ,if the rows appear here these are exact duplicates

In [77]:
df[df_clean.duplicated(subset='customer_id',keep = False)].sort_values('customer_id')

,customer_id,name,age,email,city,signup_date,salary
0,1,NaN,131.0,invalid_email,Bangalore,2023-03-07 0:00:00,400486.0
5000,1,NaN,131.0,invalid_email,Bangalore,2023-03-07 0:00:00,400486.0
1,2,Neha,19.0,neha@outlook.com,Bangalore,2023-11-12 0:00:00,NaN
5001,2,Neha,19.0,neha@outlook.com,Bangalore,2023-11-12 0:00:00,NaN
2,3,Rahul,145.0,rahul@yahoo.com,Chennai,2023-12-27 0:00:00,64898.0
...,...,...,...,...,...,...,...
47,48,John,53.0,john@yahoo.com,delhi,2023-03-22 0:00:00,66281.0
5048,49,John,-2.0,john@yahoo.com,Chennai,2022-01-26 0:00:00,83236.0
48,49,John,-2.0,john@yahoo.com,Chennai,2022-01-26 0:00:00,83236.0
49,50,John,68.0,invalid_email,Delhi,2022-11-30 0:00:00,246114.0
5049,50,John,68.0,invalid_email,Delhi,2022-11-30 0:00:00,246114.0

### from this we can see that these are exact duplicates and we must remove them

In [ ]:
df_clean.drop_duplicates(inplace = True)

In [ ]:
df_clean

## standardize text data

In [80]:
df_clean.columns

Index(['customer_id', 'name', 'age', 'email', 'city', 'signup_date', 'salary'], dtype='object')

### changing all the text format

In [82]:
df_clean['name']=df_clean['name'].str.strip().str.title()

In [83]:
df_clean['city']=df_clean['city'].str.strip().str.title()

In [ ]:
df_clean['name'].unique()

In [84]:
df_clean['city'].value_counts()

city
Delhi        1256
Mumbai       1236
Bangalore     658
Unknown       645
Chennai       637
Kolkata       618
Name: count, dtype: int64

In [85]:
df_clean.duplicated().sum()

np.int64(50)

In [86]:
df_clean.isnull().sum()

customer_id      0
name             0
age              0
email            0
city             0
signup_date    540
salary           0
dtype: int64

## Email validation

In [88]:
def add_missing_at(email):
    if isinstance(email, str) and '@' not in email:
        if 'gmail.com' in email:
            return email.replace('gmail.com', '@gmail.com')
        elif 'yahoo.com' in email:
            return email.replace('yahoo.com', '@yahoo.com')
        elif 'outlook.com' in email:
            return email.replace('outlook.com','@outlook.com')
    return email

df_clean['email'] = df['email'].apply(add_missing_at)

In [89]:
df_clean['email'].unique()

array(['invalid_email', 'neha@outlook.com', 'rahul@yahoo.com',
       'riya@outlook.com', 'neha@yahoo.com', 'neha@gmail.com',
       'sara@gmail.com', 'riya@gmail.com', 'priya@gmail.com',
       'ankit@gmail.com', 'riya@yahoo.com', 'rahul@gmail.com',
       'rahul@outlook.com', 'amit@outlook.com', 'sara@yahoo.com',
       'sara@outlook.com', 'priya@outlook.com', 'ankit@yahoo.com',
       'amit@gmail.com', 'john@yahoo.com', 'ankit@outlook.com',
       'john@outlook.com', 'amit@yahoo.com', 'john@gmail.com',
       'priya@yahoo.com'], dtype=object)

## no we have to fix all the data types

In [90]:
df_clean['age'] = df_clean['age'].astype('Int64')

In [91]:
df_clean['salary'] = df_clean['salary'].astype('Int64')

In [92]:
df_clean['signup_date']=pd.to_datetime(df_clean['signup_date'],errors = 'coerce')

In [93]:
df_clean['customer_id'] = df_clean['customer_id'].astype(int)

## Final Check

In [ ]:
df_clean.duplicated().sum()

In [ ]:
df_clean.isnull().sum()

In [ ]:
df_clean.dtypes

## reset index

In [ ]:
df_clean.reset_index(drop=True,inplace = True)

## save cleaned data in csv format

In [ ]:
df_clean.to_csv("cleaned_data_as.csv",index = False)

In [ ]:
df_clean['age'].unique()